### ISSUE TITLE
Add Other Half of Parsers

### ISSUE THREAD

**Issue by ciochetto** [TheBankingCompany/bank#7]
- [ ]  THIRD IAT ADDENDA RECORD
- [ ]  FOURTH IAT ADDENDA RECORD
- [ ]  FIFTH IAT ADDENDA RECORD
- [ ]  SIXTH IAT ADDENDA RECORD
- [ ]  SEVENTH IAT ADDENDA RECORD
- [ ]  IAT ADDENDA RECORD FOR REMITTANCE INFORMATION
- [ ]  IAT ADDENDA RECORD FOR FOREIGN CORRESPONDENT BANK INFORMATION
- [ ]  MTE ENTRY DETAIL RECORD
- [ ]  MTE ADDENDA RECORD
- [ ]  POP ENTRY DETAIL RECORD
- [ ]  POS ENTRY DETAIL RECORD
- [ ]  POS ADDENDA RECORD
- [ ]  PPD ENTRY DETAIL RECORD
- [ ]  PPD ADDENDA RECORD
- [ ]  RCK ENTRY DETAIL RECORD
- [ ]  SHR ENTRY DETAIL RECORD
- [ ]  SHR ADDENDA RECORD
- [ ]  TEL ENTRY DETAIL RECORD
- [ ]  TRC ENTRY DETAIL RECORD
- [ ]  TRX ENTRY DETAIL RECORD
- [ ]  TRX ADDENDA RECORD
- [ ]  WEB ENTRY DETAIL RECORD
- [ ]  WEB ADDENDA RECORD
- [ ]  XCK ENTRY DETAIL RECORD

**Comment by tleef** [comment]
Going to close in favor of #1
